# Generated by Django 4.1.5 on 2023-01-11 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('hair_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('price_range', models.CharField(max_length=50)),
                ('image_url', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('hair_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='curlpowerapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductHairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('hair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='curlpowerapi.hairtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='curlpowerapi.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           to='curlpowerapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='routine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='curlpowerapi.routine'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='curlpowerapi.user'),
        ),
    ]
